{docs map-over-all-combinations-of-k-vertexes}
{docs map-over-all-combinations-of-k-edges}
{docs tag-edges}
{docs tag-all-edges}
{docs untag-edges}
{docs untag-all-edges}

{docs tagged-edge-p}
{docs untagged-edge-p}
