{docs graph->dot}
{docs graph->dot-properties}
{docs vertex->dot}
{docs edge->dot}
{comment {docs (setf dot-attribute-value)}}
{docs dot-attribute-value}
{docs graph->dot-external}
{docs ensure-valid-dot-attribute}
{docs write-name-for-dot}
