{docs edge-count}
{docs vertex-count}
{docs source-edge-count}
{docs target-edge-count}
{docs number-of-neighbors}
{docs has-children-p}
{docs has-parent-p}

{docs source-vertex}
{docs target-vertex}
{docs undirected-edge-p}
{docs directed-edge-p}
{docs make-vertex-edges-container}
{docs other-vertex}
{docs vertices-share-edge-p}

{docs out-edge-for-vertex-p}
{docs in-undirected-cycle-p}
{docs adjacentp}
{docs depth}
{docs edge-lessp-by-weight}
{docs edge-lessp-by-direction}
{docs weight}

{docs rootp}
{docs in-cycle-p}
{docs any-undirected-cycle-p}
