{docs iterate-children}
{docs iterate-parents}
{docs iterate-neighbors}
{docs iterate-edges}
{docs iterate-source-edges}
{docs iterate-target-edges}
{docs source-edges}
{docs target-edges}
{docs child-vertexes}
{docs parent-vertexes}
{docs neighbor-vertexes}
{docs iterate-vertexes}
{docs edges}
{docs vertexes}

