{docs make-graph}
{docs add-edges-to-graph}
{docs add-vertex}
{docs add-edge}
{docs add-edge-between-vertexes}
{docs delete-edge}
{docs delete-all-edges}
{docs delete-edge-between-vertexes}
{docs delete-vertex}
{docs replace-vertex}
{docs add-edge-to-vertex}

{docs make-vertex-container}
{docs make-edge-container}
{docs make-edge-for-graph}
{docs make-vertex-for-graph}
{docs make-graph-from-vertexes}