Requires [cl-variants][].

{docs generate-gnm}
{docs generate-gnp}
{docs generate-undirected-graph-via-assortativity-matrix}
{docs generate-undirected-graph-via-vertex-probabilities}
{docs generate-scale-free-graph}
{docs generate-assortative-graph-with-degree-distributions}
{docs generate-simple-preferential-attachment-graph}
{docs generate-preferential-attachment-graph}

{docs graph-edge-mixture-matrix}
{docs graph-mixing-matrix}
