{docs find-vertex}
{docs search-for-vertex}
{docs find-edge}
{docs find-edge-between-vertexes}
{docs find-vertex-if}
{docs find-edge-if}
{docs find-edges-if}
{docs find-vertexes-if}
{docs find-edge-between-vertexes-if}
