{include resources/header.md}
{set-property title "CL-Graph"}

   [1]: http://common-lisp.net/project/cl-containers/shared/metabang-2.png (metabang.com)
   [2]: http://www.metabang.com/ (metabang.com)

<div class="contents">
<div class="system-links">

  * [Mailing Lists][3]
  * [Getting it][4]
{remark  * [Documentation][5] }
  * [News][6]
{remark  * [Test results][tr]}
  * [Changelog][7]

   [3]: #mailing-lists
   [4]: #downloads
   [5]: documentation/ (documentation link)
   [6]: #news
   [7]: changelog.html
   [tr]: test-report.html

</div>
<div class="system-description">

### What it is

CL-Graph is a Common Lisp library for manipulating graphs and
running graph algorithms. {remark [TINAA][] documentation for
CL-Graph is [available][9].} Check out the [user's guide](user-guide.html)
for some very old and yet still preliminary documentation. 

The style-sheet is currently completely bogus. Apologies in advance.

   [9]: http://common-lisp.net/project/cl-graph/documentation/

{anchor mailing-lists}

### Mailing Lists

  * [cl-graph-devel][devel-list]: A list for questions,
    patches, bug reports, and so on; It's for everything.

{anchor downloads}

### Where is it

metabang.com is switching from [darcs][] to [git][]
for source control; the current cl-graph repository is on
[github][github-cl-graph] and you can clone it using:

    git clone git://github.com/gwkkwg/cl-graph

(note that you'll also
need to get several other bits and pieces to get CL-Graph to
work. The commands are listed below:

    git clone git://github.com/gwkkwg/metabang-bind
    git clone git://github.com/gwkkwg/metatilities-base
    git clone git://github.com/gwkkwg/moptilities

You might also want [dynamic-classes][]:

    git clone git://github.com/gwkkwg/dynamic-classes

CL-Graph (and friends) should also be [ASDF
installable][asdf-install]. Its CLiki home is right
[where][cliki-home] you'd expect.

There's also a handy [gzipped tar file][tarball].

### What is happening

8 January 2011
Moved to github; minor cleanup.

2 Feb 2006
Lots of new [CL-Graph][16] documentation.

   [16]: http://common-lisp.net/project/cl-graph/documentation/

25 Nov 2005
Wrote a mini tutorial and published it on [unCLog][17].

   [17]: http://www.metabang.com/unclog/publisha/atinybit.html

10 Nov 2005
Initial setup.

</div>
</div>

{include resources/footer.md}

